#!/usr/bin/env python3
"""Package the distributable artifacts.

Two shapes, one client source. Catalog discovery happens through MCP.

  dist/mekomil.zip the uploadable skill bundle. claude.ai expects a .zip whose
                   root holds ONE folder with SKILL.md at its top level.
  plugin/          the Claude Code plugin -- skill and connector in one install.
                   Committed to the tree, because `/plugin marketplace add`
                   reads the git checkout; it is generated, so CI checks it has
                   not drifted from the root copies.
"""
import json, os, shutil, zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(ROOT, "dist")
PLUGIN = os.path.join(ROOT, "plugin")
MCP_URL = "https://mekomil-mcp.vercel.app/api/mcp"
SOURCE_REPO = "https://github.com/ilanvys/mekomil"
SITE_URL = "https://ilanvys.github.io/mekomil/"

VERSION = "0.2.0"
DESCRIPTION = ("Finds the Israeli skill that fits your question in the open skills-il catalog, "
               "loads it for that one task, and forgets it. Hebrew-first: tax, pensions, "
               "ביטוח לאומי, government forms, law, RTL and Israeli formats.")


def build_zip():
    os.makedirs(DIST, exist_ok=True)
    out = os.path.join(DIST, "mekomil.zip")
    files = [("skill/SKILL.md", "SKILL.md")]
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for src, arc in files:
            info = zipfile.ZipInfo(f"mekomil/{arc}", date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            with open(os.path.join(ROOT, src), "rb") as source:
                z.writestr(info, source.read())
    print(f"{out}  ({os.path.getsize(out):,} bytes, {len(files)} files)")


def write(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(data if isinstance(data, str) else json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def build_plugin():
    # Regenerated wholesale: a stale file left behind is the failure mode a
    # generated-and-committed directory actually has.
    if os.path.isdir(PLUGIN):
        shutil.rmtree(PLUGIN)

    write(os.path.join(PLUGIN, ".claude-plugin", "plugin.json"), {
        "name": "mekomil",
        "description": DESCRIPTION,
        "version": VERSION,
        "author": {"name": "ilanvys", "url": SOURCE_REPO},
        "homepage": SITE_URL,
        "license": "MIT",
    })

    # The connector. One address, and it is the only thing here that will ever
    # need changing when the service address moves.
    write(os.path.join(PLUGIN, ".mcp.json"),
          {"mcpServers": {"mekomil": {"type": "http", "url": MCP_URL}}})

    skill = os.path.join(PLUGIN, "skills", "mekomil")
    os.makedirs(skill, exist_ok=True)
    shutil.copy(os.path.join(ROOT, "skill", "SKILL.md"), os.path.join(skill, "SKILL.md"))
    write(os.path.join(PLUGIN, "README.md"),
          "# mekomIL — Claude Code plugin\n\n"
          "**Generated by `tools/build_bundles.py`. Do not edit by hand.**\n"
          "`skill/SKILL.md` is the client source. The catalog comes from MCP.\n\n"
          "Installs both halves in one command — the skill that decides which Israeli guide a\n"
          "question needs, and the connector that fetches it:\n\n"
          "```\n/plugin marketplace add ilanvys/mekomil\n/plugin install mekomil@mekomil\n```\n\n"
          f"The connector points at `{MCP_URL}`. Catalog metadata is served by MCP; skill\n"
          "content is fetched from the public skills-il repos. MIT.\n")

    n = 4
    print(f"{PLUGIN}/  ({n} files, skill + connector)")


def build_marketplace():
    # The repo doubles as a single-plugin marketplace, so `/plugin marketplace
    # add ilanvys/mekomil` is the discovery step.
    write(os.path.join(ROOT, ".claude-plugin", "marketplace.json"), {
        "name": "mekomil",
        "description": "The mekomIL skill and its fetch connector, in one install.",
        "owner": {"name": "ilanvys", "url": SOURCE_REPO},
        "plugins": [{
            "name": "mekomil",
            "description": DESCRIPTION,
            "author": {"name": "ilanvys"},
            "source": "./plugin",
            "category": "productivity",
            "homepage": SITE_URL,
        }],
    })
    print(f"{ROOT}/.claude-plugin/marketplace.json")


if __name__ == "__main__":
    build_zip()
    build_plugin()
    build_marketplace()
